create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id  serial not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id  serial not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id  serial not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
create table book (id varchar(255) not null, category int4 not null, img varchar(255) not null, name varchar(255) not null, price int4 not null, quantity int4 not null, primary key (id));
